pipeline{
  agent any


  tools{
    maven 'maven 3.9.6'
  }

  stages{
    stage("build"){
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }  

      }   


    }

    stage("test"){
      steps{
        echo "Running Unit Tests on worker app"
        dir('worker'){
          sh 'mvn clean test'

      }

    }

    stage("package"){
      steps{
        echo 'Packaging Worker App'
        dir('worker'){
          sh 'mvn package'
   
      }

    }
  
  }
  
  post{
    always{
      echo 'Building multibranch pileine for worker completed'
    }
  
  }
}
